Repository heremaps/gluecodium, pull requests merged in 2020-11, with the labels that each got.

#576 Adds tests that C++ modules were able to be built
  cmake/tests/run_tests.cmake
  cmake/tests/unit/apigen_generate/object-modules/CMakeLists.txt
  cmake/tests/unit/apigen_generate/object-modules/cpp/BarImpl.cpp
  cmake/tests/unit/apigen_generate/object-modules/cpp/FooImpl.cpp
  cmake/tests/unit/apigen_generate/object-modules/lime/bar.lime
  cmake/tests/unit/apigen_generate/object-modules/lime/foo.lime
  cmake/tests/unit/apigen_generate/shared-modules/CMakeLists.txt
  cmake/tests/unit/apigen_generate/shared-modules/cpp/BarImpl.cpp
  cmake/tests/unit/apigen_generate/shared-modules/cpp/FooImpl.cpp
  cmake/tests/unit/apigen_generate/shared-modules/lime/bar.lime
  cmake/tests/unit/apigen_generate/shared-modules/lime/foo.lime
  cmake/tests/utils/check_symbols_exists_after_build.cmake
Labels: cmake

#577 Add CBridge header reference files to "structs" smoke test
  gluecodium/src/test/resources/smoke/structs/output/cbridge/include/smoke/cbridge_Structs.h
  gluecodium/src/test/resources/smoke/structs/output/cbridge/include/smoke/cbridge_StructsWithMethods.h
  gluecodium/src/test/resources/smoke/structs/output/cbridge/include/smoke/cbridge_StructsWithMethodsInterface.h
Labels: swift

#578 Add support for nesting enums inside structs to LimeIDL
  docs/lime_idl.md
  gluecodium/src/main/java/com/here/gluecodium/generator/common/LimeModelFilter.kt
  gluecodium/src/test/resources/smoke/nesting/input/NestingInStruct.lime
  gluecodium/src/test/resources/smoke/nesting/output/lime/smoke/OuterStruct.lime
  lime-loader/src/main/antlr/LimeParser.g4
  lime-loader/src/main/java/com/here/gluecodium/loader/AntlrLimeModelBuilder.kt
  lime-runtime/src/main/java/com/here/gluecodium/model/lime/LimeStruct.kt
Labels: enhancement

#580 Add support for nesting enums inside structs in C++
  gluecodium/src/main/resources/templates/cpp/CppStruct.mustache
  gluecodium/src/main/resources/templates/cpp/CppStructImpl.mustache
  gluecodium/src/test/resources/smoke/nesting/output/cpp/include/smoke/OuterStruct.h
Labels: c++, enhancement

#581 Add support for nesting enums inside structs in Java
  gluecodium/src/test/resources/smoke/nesting/input/NestingInStruct.lime
  gluecodium/src/test/resources/smoke/nesting/output/android/com/example/smoke/OuterStruct.java
  gluecodium/src/test/resources/smoke/nesting/output/android/jni/com_example_smoke_OuterStruct_InnerEnum__Conversion.cpp
  gluecodium/src/test/resources/smoke/nesting/output/lime/smoke/OuterStruct.lime
Labels: enhancement, java

#583 Add support for nesting enums inside structs in Dart
  gluecodium/src/main/resources/templates/dart/DartStruct.mustache
  gluecodium/src/test/resources/smoke/nesting/input/NestingInStruct.lime
  gluecodium/src/test/resources/smoke/nesting/output/dart/ffi/ffi_smoke_OuterStruct.cpp
  gluecodium/src/test/resources/smoke/nesting/output/dart/ffi/ffi_smoke_OuterStruct.h
  gluecodium/src/test/resources/smoke/nesting/output/dart/lib/src/smoke/outer_struct.dart
  gluecodium/src/test/resources/smoke/nesting/output/lime/smoke/OuterStruct.lime
Labels: dart, enhancement

#584 Add support for nesting enums inside structs in Swift
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeModelBuilder.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/swift/SwiftModelBuilder.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CStruct.kt
  gluecodium/src/main/java/com/here/gluecodium/model/swift/SwiftStruct.kt
  gluecodium/src/main/resources/templates/cbridge/StructHeader.mustache
  gluecodium/src/main/resources/templates/swift/Struct.mustache
  gluecodium/src/main/resources/templates/swift/StructConversion.mustache
  gluecodium/src/test/resources/smoke/nesting/input/NestingInStruct.lime
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/include/smoke/cbridge_OuterStruct.h
  gluecodium/src/test/resources/smoke/nesting/output/lime/smoke/OuterStruct.lime
  gluecodium/src/test/resources/smoke/nesting/output/swift/smoke/OuterStruct.swift
Labels: enhancement, swift

#588 Fix indentation in CBridge struct field getter
  gluecodium/src/main/resources/templates/cbridge/StructImplementation.mustache
  gluecodium/src/test/resources/namespace_smoke/basic/output/cbridge/src/root/space/smoke/cbridge_BasicTypes.cpp
  gluecodium/src/test/resources/smoke/dates/output/cbridge/src/smoke/cbridge_Dates.cpp
  gluecodium/src/test/resources/smoke/equatable/output/cbridge/src/smoke/cbridge_EquatableClass.cpp
  gluecodium/src/test/resources/smoke/extensions/output/cbridge/src/smoke/cbridge_Extensions__extension.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_ExternalClass.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_ExternalInterface.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_Structs.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/smoke/cbridge_GenericTypesWithBasicTypes.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/smoke/cbridge_GenericTypesWithCompoundTypes.cpp
  gluecodium/src/test/resources/smoke/instances/output/cbridge/src/smoke/cbridge_StructWithClass.cpp
  gluecodium/src/test/resources/smoke/instances/output/cbridge/src/smoke/cbridge_StructWithInterface.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_CalculatorListener.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_ListenerWithProperties.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_ListenersWithReturnValues.cpp
  gluecodium/src/test/resources/smoke/locales/output/cbridge/src/smoke/cbridge_Locales.cpp
  gluecodium/src/test/resources/smoke/name_rules/output/cbridge/src/namerules/cbridge_NameRules.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_FreePoint.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_LevelOne.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_OuterStruct.cpp
  gluecodium/src/test/resources/smoke/nullable/output/cbridge/src/smoke/cbridge_NullableCollectionsStruct.cpp
  gluecodium/src/test/resources/smoke/structs/output/cbridge/src/smoke/cbridge_Structs.cpp
  gluecodium/src/test/resources/smoke/structs/output/cbridge/src/smoke/cbridge_StructsWithMethods.cpp
  gluecodium/src/test/resources/smoke/structs/output/cbridge/src/smoke/cbridge_StructsWithMethodsInterface.cpp
Labels: swift

#591 Add CBridge header reference files for "instances" smoke test
  gluecodium/src/test/resources/smoke/instances/output/cbridge/include/smoke/cbridge_SimpleClass.h
  gluecodium/src/test/resources/smoke/instances/output/cbridge/include/smoke/cbridge_SimpleInterface.h
Labels: swift

#593 Fix whitespace in generic type conversions for CBridge
  gluecodium/src/main/resources/templates/cbridge/ArrayFunctionImplementations.mustache
  gluecodium/src/main/resources/templates/cbridge/MapFunctionImplementations.mustache
  gluecodium/src/main/resources/templates/cbridge/SetFunctionImplementations.mustache
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/GenericCollections.cpp
  gluecodium/src/test/resources/smoke/locales/output/cbridge/src/GenericCollections.cpp
Labels: swift

#597 Normalize whitespace for C++ template types in CBridge
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeTypeMapper.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cbridge/CBridgeTypeMapperTest.kt
  gluecodium/src/test/resources/namespace_smoke/basic/output/cbridge/src/root/space/smoke/cbridge_Basic.cpp
  gluecodium/src/test/resources/smoke/basic_types/output/cbridge/src/smoke/cbridge_BasicTypes.cpp
  gluecodium/src/test/resources/smoke/constructors/output/cbridge/src/smoke/cbridge_Constructors.cpp
  gluecodium/src/test/resources/smoke/dates/output/cbridge/src/smoke/cbridge_Dates.cpp
  gluecodium/src/test/resources/smoke/equatable/output/cbridge/src/smoke/cbridge_EquatableClass.cpp
  gluecodium/src/test/resources/smoke/equatable/output/cbridge/src/smoke/cbridge_EquatableInterface.cpp
  gluecodium/src/test/resources/smoke/equatable/output/cbridge/src/smoke/cbridge_PointerEquatableClass.cpp
  gluecodium/src/test/resources/smoke/errors/output/cbridge/src/smoke/cbridge_Errors.cpp
  gluecodium/src/test/resources/smoke/errors/output/cbridge/src/smoke/cbridge_ErrorsInterface.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_Enums.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_ExternalClass.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_ExternalInterface.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_Structs.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_UseSwiftExternalTypes.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/GenericCollections.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/smoke/cbridge_GenericTypesWithBasicTypes.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/smoke/cbridge_GenericTypesWithCompoundTypes.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/smoke/cbridge_GenericTypesWithGenericTypes.cpp
  gluecodium/src/test/resources/smoke/inheritance/output/cbridge/src/smoke/cbridge_ChildClassFromClass.cpp
  gluecodium/src/test/resources/smoke/inheritance/output/cbridge/src/smoke/cbridge_ChildClassFromInterface.cpp
  gluecodium/src/test/resources/smoke/inheritance/output/cbridge/src/smoke/cbridge_ChildInterface.cpp
  gluecodium/src/test/resources/smoke/instances/output/cbridge/src/smoke/cbridge_SimpleClass.cpp
  gluecodium/src/test/resources/smoke/instances/output/cbridge/src/smoke/cbridge_SimpleInterface.cpp
  gluecodium/src/test/resources/smoke/instances/output/cbridge/src/smoke/cbridge_StructWithClass.cpp
  gluecodium/src/test/resources/smoke/instances/output/cbridge/src/smoke/cbridge_StructWithInterface.cpp
  gluecodium/src/test/resources/smoke/lambdas/output/cbridge/src/smoke/cbridge_Lambdas.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_CalculatorListener.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_ListenerWithProperties.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_ListenersWithReturnValues.cpp
  gluecodium/src/test/resources/smoke/listeners/output/cbridge/src/smoke/cbridge_Weakling.cpp
  gluecodium/src/test/resources/smoke/locales/output/cbridge/src/GenericCollections.cpp
  gluecodium/src/test/resources/smoke/locales/output/cbridge/src/smoke/cbridge_Locales.cpp
  gluecodium/src/test/resources/smoke/name_rules/output/cbridge/src/namerules/cbridge_NameRules.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_LevelOne.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_OuterClass.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_OuterInterface.cpp
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_OuterStruct.cpp
  gluecodium/src/test/resources/smoke/nullable/output/cbridge/src/smoke/cbridge_NullableCollectionsStruct.cpp
  gluecodium/src/test/resources/smoke/skip/output/cbridge/src/smoke/cbridge_SkipProxy.cpp
  gluecodium/src/test/resources/smoke/structs/output/cbridge/src/smoke/cbridge_Structs.cpp
  gluecodium/src/test/resources/smoke/structs/output/cbridge/src/smoke/cbridge_StructsWithMethodsInterface.cpp
Labels: swift

#598 Add CBridge enum header files to smoke tests
  gluecodium/src/test/resources/smoke/enums/output/cbridge/include/smoke/cbridge_EnumsInTypeCollectionInterface.h
  gluecodium/src/test/resources/smoke/errors/input/Errors.lime
  gluecodium/src/test/resources/smoke/errors/output/cbridge/include/smoke/cbridge_UseTcException.h
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/include/smoke/cbridge_Enums.h
Labels: swift

#601 Fix stack overflow in getAllFieldTypes()
  CHANGELOG.md
  gluecodium/src/test/resources/smoke/structs/input/RecursiveStructs.lime
  lime-runtime/src/main/java/com/here/gluecodium/model/lime/LimeTypeHelper.kt
Labels: bug

#604 Temporarily disable Dart builds on Travis
  .travis.yml
Labels: dart, travis

#610 Fix typo in get_field_value() for Locale in JNI
  CHANGELOG.md
  gluecodium/src/main/resources/templates/jni/utils/FieldAccessMethodsHeader.mustache
Labels: bug, java

#611 Delay exception throwing in JNI until the end of method scope
  CHANGELOG.md
  examples/libhello/CMakeLists.txt
  examples/libhello/lime/test/ErrorsWithNonTrivialType.lime
  examples/libhello/src/test/ErrorsWithNonTrivialType.cpp
  examples/platforms/android/app/src/test/java/com/here/android/test/ErrorsTest.java
  gluecodium/src/main/java/com/here/gluecodium/generator/java/JavaGeneratorSuite.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/jni/JniIncludeResolver.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/jni/JniTemplates.kt
  gluecodium/src/main/resources/templates/jni/Implementation.mustache
  gluecodium/src/main/resources/templates/jni/utils/JniExceptionThrowerHeader.mustache
  gluecodium/src/test/resources/smoke/constructors/output/android/jni/com_example_smoke_Constructors.cpp
  gluecodium/src/test/resources/smoke/errors/output/android/jni/com_example_smoke_Errors.cpp
  gluecodium/src/test/resources/smoke/name_rules/output/android/jni/com_example_namerules_NAME_RULES_DROID.cpp
  gluecodium/src/test/resources/smoke/structs/output/android/jni/com_example_smoke_StructsWithMethodsInterface_Vector3.cpp
  gluecodium/src/test/resources/smoke/structs/output/android/jni/com_example_smoke_Vector.cpp
Labels: bug, java

#613 Add CBridge tests for external types usage
  gluecodium/src/test/resources/smoke/external_types/input/ExternalTypes.lime
  gluecodium/src/test/resources/smoke/external_types/input/UseCppExternalTypes.lime
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/include/dontsmoke/cbridge_UseCppExternalTypes.h
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/dontsmoke/cbridge_UseCppExternalTypes.cpp
  gluecodium/src/test/resources/smoke/external_types/output/cbridge/src/smoke/cbridge_ExternalTypeInTypesCollection.cpp
Labels: swift

#614 Makes Gluecodium to be compatible with CMake 3.19 and Xcode 11.x
  cmake/modules/gluecodium/gluecodium/Generate.cmake
Labels: cmake

#615 Add CBridge smoke test for top-level lambda definition
  gluecodium/src/test/resources/smoke/nesting/input/FreeTypes.lime
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/include/smoke/cbridge_FreeLambda.h
  gluecodium/src/test/resources/smoke/nesting/output/cbridge/src/smoke/cbridge_FreeLambda.cpp
Labels: swift

#616 Add more reference files for CBridge smoke tests
  gluecodium/src/test/resources/smoke/constants/output/cbridge/src/GenericCollections.cpp
  gluecodium/src/test/resources/smoke/enums/output/cbridge/src/smoke/cbridge_Enums.cpp
  gluecodium/src/test/resources/smoke/equatable/output/cbridge/include/smoke/cbridge_EquatableClass.h
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/include/GenericCollections.h
  gluecodium/src/test/resources/smoke/inheritance/output/cbridge/include/smoke/cbridge_ChildClassFromClass.h
  gluecodium/src/test/resources/smoke/inheritance/output/cbridge/include/smoke/cbridge_ChildInterface.h
  gluecodium/src/test/resources/smoke/nullable/output/cbridge/src/smoke/cbridge_Nullable.cpp
Labels: swift

#619 Add CBridge smoke test for inherited generics
  gluecodium/src/test/java/com/here/gluecodium/AcceptanceTestBase.kt
  gluecodium/src/test/java/com/here/gluecodium/SmokeTest.kt
  gluecodium/src/test/resources/smoke/generic_types/auxiliary/AuxParent.lime
  gluecodium/src/test/resources/smoke/generic_types/input/GenericTypes.lime
  gluecodium/src/test/resources/smoke/generic_types/input/commandlineoptions.txt
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/include/GenericCollections.h
  gluecodium/src/test/resources/smoke/generic_types/output/cbridge/src/GenericCollections.cpp
  gluecodium/src/test/resources/smoke/generic_types/output/swift/Collections.swift
Labels: swift

#622 Remove CBridge model
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeComponents.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeGenerator.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeHeaderIncludeResolver.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeImplIncludeResolver.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeModelBuilder.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeNameRules.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeTypeMapper.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CCollectionsGenerator.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CppArrayTypeInfo.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CppMapTypeInfo.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CppSetTypeInfo.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CppTypeInfo.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CArray.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CBridgeIncludeResolver.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CCollectionType.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CElement.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CEnum.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CField.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CFunction.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CInterface.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CMap.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CParameter.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CSet.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CStruct.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/CType.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cbridge/package-info.java
  gluecodium/src/test/java/com/here/gluecodium/generator/cbridge/CBridgeModelBuilderTest.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cbridge/CBridgeTypeMapperTest.kt
Labels: swift

#623 Remove C++ model
  gluecodium/src/main/java/com/here/gluecodium/generator/cpp/CppForwardDeclarationGroup.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cpp/CppGeneratorSuite.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cpp/CppModelBuilder.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/cpp/CppTypeMapper.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppClass.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppComplexTypeRef.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppConstant.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppElement.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppElementWithComment.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppElementWithIncludes.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppEnum.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppEnumItem.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppExternableElement.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppField.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppFunctionTypeRef.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppInheritance.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppMethod.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppParameter.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppPrimitiveTypeRef.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppStruct.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppTemplateTypeRef.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppTypeDefRef.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppTypeRef.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppTypedElement.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppUsing.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/CppValue.kt
  gluecodium/src/main/java/com/here/gluecodium/model/cpp/package-info.java
  gluecodium/src/test/java/com/here/gluecodium/generator/cpp/CppIncludeResolverTest.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cpp/CppModelBuilderCommentsTest.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cpp/CppModelBuilderTest.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cpp/CppModelBuilderValueTest.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cpp/CppNameResolverTest.kt
  gluecodium/src/test/java/com/here/gluecodium/generator/cpp/CppTypeMapperTest.kt
Labels: c++

#624 Extract GenericTypesCollector into a dedicated class
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeGenerator.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/common/GenericTypesCollector.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/dart/DartGeneratorSuite.kt
  gluecodium/src/test/java/com/here/gluecodium/SmokeTest.kt
Labels: dart, swift

#625 Fix Swift overloads resolution for platform names
  CHANGELOG.md
  examples/libhello/lime/test/MethodOverloads.lime
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeNameResolver.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/swift/SwiftGenerator.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/swift/SwiftSignatureResolver.kt
  gluecodium/src/test/resources/smoke/method_overloads/input/MethodOverloads.lime
  gluecodium/src/test/resources/smoke/method_overloads/output/cbridge/include/smoke/cbridge_SwiftMethodOverloads.h
  gluecodium/src/test/resources/smoke/method_overloads/output/cbridge/src/smoke/cbridge_SwiftMethodOverloads.cpp
  gluecodium/src/test/resources/smoke/method_overloads/output/swift/smoke/SwiftMethodOverloads.swift
Labels: bug, swift

#629 Fix missing include for interfaces in Dart FFI
  CHANGELOG.md
  gluecodium/src/main/java/com/here/gluecodium/generator/dart/DartGeneratorSuite.kt
  gluecodium/src/main/java/com/here/gluecodium/generator/ffi/FfiCppIncludeResolver.kt
  gluecodium/src/main/resources/templates/ffi/FfiProxyDeclaration.mustache
  gluecodium/src/test/resources/smoke/constructors/output/dart/ffi/ffi_smoke_Constructors.cpp
  gluecodium/src/test/resources/smoke/equatable/output/dart/ffi/ffi_smoke_EquatableInterface.cpp
  gluecodium/src/test/resources/smoke/errors/output/dart/ffi/ffi_smoke_ErrorsInterface.cpp
  gluecodium/src/test/resources/smoke/external_types/input/ExternalTypes.lime
  gluecodium/src/test/resources/smoke/external_types/output/dart/ffi/ffi_smoke_ExternalInterface.cpp
  gluecodium/src/test/resources/smoke/external_types/output/dart/ffi/ffi_smoke_ExternalWithNoFunctions.cpp
  gluecodium/src/test/resources/smoke/instances/output/dart/ffi/ffi_smoke_SimpleInterface.cpp
  gluecodium/src/test/resources/smoke/listeners/output/dart/ffi/ffi_smoke_CalculatorListener.cpp
  gluecodium/src/test/resources/smoke/listeners/output/dart/ffi/ffi_smoke_ListenerWithProperties.cpp
  gluecodium/src/test/resources/smoke/listeners/output/dart/ffi/ffi_smoke_ListenersWithReturnValues.cpp
  gluecodium/src/test/resources/smoke/nesting/output/dart/ffi/ffi_smoke_OuterClass.cpp
  gluecodium/src/test/resources/smoke/nesting/output/dart/ffi/ffi_smoke_OuterInterface.cpp
  gluecodium/src/test/resources/smoke/nesting/output/dart/ffi/ffi_smoke_OuterStruct.cpp
  gluecodium/src/test/resources/smoke/skip/output/dart/ffi/ffi_smoke_SkipProxy.cpp
Labels: bug, dart

#631 Add tests for Java overloads resolution for platform names
  examples/libhello/lime/test/MethodOverloads.lime
  gluecodium/src/test/resources/smoke/method_overloads/input/MethodOverloads.lime
  gluecodium/src/test/resources/smoke/method_overloads/output/android/jni/com_example_smoke_JavaMethodOverloads.cpp
  gluecodium/src/test/resources/smoke/method_overloads/output/android/jni/com_example_smoke_JavaMethodOverloads.h
Labels: java

#632 Add tests for potential Dart name clash
  examples/libhello/lime/test/MethodOverloads.lime
  gluecodium/src/test/resources/smoke/method_overloads/input/MethodOverloads.lime
  gluecodium/src/test/resources/smoke/method_overloads/output/dart/ffi/ffi_smoke_SpecialNamesInterface.cpp
Labels: dart

#636 Remove CBridge refactoring leftovers
  gluecodium/src/main/java/com/here/gluecodium/generator/cbridge/CBridgeNameResolver.kt
Labels: swift
